---
title: "Script IMDB"
author: "Alexandra Salo and Sofía Villamil"
date: "2024-03-03"
output: html_document
---

## IMDB - Web scraping

```{r}
rm(list = ls())
```

### Libraries

```{r}
library(rvest)
library(httr)
library(dplyr)
library(tidytext)
library(purrr)
library(ggplot2)
library(scales)

```

### Link to the website

```{r}
link <- "https://www.imdb.com/chart/top"
```

```{r}
set_config(
  #user_agent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36; Sofia Villamil / sofia.v1999@gmail.com"))
  user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36, Alexandra Salo, alexandra.rose.salo@gmail.com"))

Top250_website <- link %>% read_html()
```

### Titles

```{r}
# Make an HTTP GET request with 'Accept-Language' header set to 'en'
response <- GET(link, add_headers("Accept-Language" = "en-US,en;q=0.5"))

# Parse the HTML content from the response
Top250_website <- content(response, "text") %>% read_html()

# Select the movie title nodes
movie_title_nodes <- html_nodes(Top250_website, "h3.ipc-title__text")

# Extracting movie titles
movie_titles <- html_text(movie_title_nodes)

length(movie_title_nodes) # I have node I don't need.

# Extracting the titles I need only
movie_titles <- html_text(movie_title_nodes)[2:251]
print(movie_titles)

```

### URL

```{r}
movie_link_nodes <- html_nodes(Top250_website, 'a.ipc-title-link-wrapper')
movie_urls <- html_attr(movie_link_nodes, 'href')

full_movie_urls <- paste0("https://www.imdb.com", movie_urls)
full_movie_urls <- full_movie_urls[1:250]

print(full_movie_urls)

```

### Getting the information for one specific URL

```{r}
url <- "https://www.imdb.com/title/tt23849204/?ref_=chttp_t_54" 

scrape_movie_details <- function(url) {
  movie_page <- read_html(url)
  #Title
  title <- movie_page %>%
    html_nodes('span.hero__primary-text') %>%
    html_text(trim = TRUE)

  # Year
  year <- movie_page %>%
    html_nodes('a.ipc-link--baseAlt[href*="/releaseinfo"]') %>%
    html_text(trim = TRUE) %>%
    .[1]

  # MPAA Rating
  mpaa_rating_node <- movie_page %>%
    html_nodes('li.ipc-inline-list__item a[href*="/parentalguide/certificates"]') 

  mpaa_rating <- if (length(mpaa_rating_node) > 0) html_text(mpaa_rating_node[1], trim = TRUE) else NA


  # Duration
  duration_nodes <- movie_page %>%
    html_nodes('ul.ipc-inline-list li.ipc-inline-list__item') %>%
    html_text(trim = TRUE)
  
  duration <- grep("^[0-9]+h [0-9]+m$", duration_nodes, value = TRUE)
  duration <- if (length(duration) > 0) tail(duration, n = 1) else NA

  # IMDb Score
  imdb_score <- movie_page %>%
    html_nodes('span.sc-bde20123-1') %>%
    html_text(trim = TRUE) %>%
    .[1]

  # Director
  director <- movie_page %>%
    html_nodes('a.ipc-metadata-list-item__list-content-item--link[href*="/name"]') %>%
    html_text(trim = TRUE) %>%
    .[1] 

  # First Actor
  first_actor <- movie_page %>%
    html_nodes('a[data-testid="title-cast-item__actor"]') %>%
    html_text(trim = TRUE) %>%
    .[1]

  # Second Actor
  second_actor <- movie_page %>%
    html_nodes('a[data-testid="title-cast-item__actor"]') %>%
    html_text(trim = TRUE) %>%
    .[2]

  # First Writer
  first_writer <- movie_page %>%
    html_nodes('a.ipc-metadata-list-item__list-content-item--link[href*="/name"]') %>%
    html_text(trim = TRUE) %>%
    .[2]

  # Second Writer
  second_writer <- movie_page %>%
    html_nodes('a.ipc-metadata-list-item__list-content-item--link[href*="/name"]') %>%
    html_text(trim = TRUE) %>%
    .[3] 
  
  # Release Date
  release_date <- movie_page %>%
    html_nodes('a.ipc-metadata-list-item__list-content-item--link[href*="/releaseinfo"]') %>%
    html_text(trim = TRUE)%>%
    .[1] 
  
  # Genres
  genre <- movie_page %>%
    html_nodes('a.ipc-chip.ipc-chip--on-baseAlt') %>%
    html_nodes('span.ipc-chip__text') %>%
    html_text(trim = TRUE)%>%
    .[1] 
 
  # Budget
  budget <- movie_page %>%
    html_node('[data-testid="title-boxoffice-budget"] .ipc-metadata-list-item__list-content-item') %>%
    html_text(trim = TRUE)

  # Gross Worldwide
  gross_worldwide <- movie_page %>%
    html_node('[data-testid="title-boxoffice-cumulativeworldwidegross"] .ipc-metadata-list-item__list-content-item') %>%
    html_text(trim = TRUE)

  
  # Title of the Feature Review
  review_title <- movie_page %>%
    html_node('span[data-testid="review-summary"]') %>%
    html_text(trim = TRUE)%>%
    .[1]
  
   # Feature Review
  feature_review <- movie_page %>%
    html_node('div[data-testid="review-overflow"] .ipc-html-content-inner-div') %>%
    html_text(trim = TRUE)

  # Number of Awards and Nominations
  awards_and_nominations <- movie_page %>%
    html_node('span.ipc-metadata-list-item__list-content-item') %>%
    html_text(trim = TRUE)
  
  oscars_nominations <- movie_page %>%
    html_node('a.ipc-metadata-list-item__label--link[aria-label="See more awards and nominations"]')%>%
    html_text(trim = TRUE)

  list(
    Title = title, Year = year, MPAA = mpaa_rating, Duration = duration, IMDbscore = imdb_score, Director = director,
    FirstActor = first_actor, SecondActor = second_actor, FirstWriter = first_writer,
    SecondWriter = second_writer, ReleaseDate = release_date, Genre=genre, Budget = budget,
    GrossWorldwide = gross_worldwide, TitleReview = review_title, FeatureReview = feature_review,
    AwardsAndNominations = awards_and_nominations, Oscar_Information = oscars_nominations
  )
}

movie_details <- scrape_movie_details(url)
print(movie_details)
```

### Testing for 5 URLS to see the data structure

```{r}
movies_df <- data.frame(
  Title = character(),
  Year = character(),
  MPAA = character(),
  Duration = character(),
  IMDbscore = character(),
  Director = character(),
  FirstActor = character(),
  SecondActor = character(),
  FirstWriter = character(),
  SecondWriter = character(),
  ReleaseDate = character(),
  Genre = character(),
  Budget = character(),
  GrossWorldwide = character(),
  TitleReview = character(),
  FeatureReview = character(),
  AwardsAndNominations = character(),
  Oscar_Information = character(),
  stringsAsFactors = FALSE
)

test_urls <- head(full_movie_urls, 5)

for (url in test_urls) {
  print(paste("Processing:", url))
  Sys.sleep(runif(1, 1, 3)) 
  movie_details <- tryCatch({
    scrape_movie_details(url)
  }, error = function(e) {
    print(paste("Error in processing:", url))
    print(e)
    return(NULL)
  })
  
  if (!is.null(movie_details)) {
    movie_details_df <- as.data.frame(matrix(unlist(movie_details), nrow = 1, byrow = TRUE), stringsAsFactors = FALSE)
    colnames(movie_details_df) <- names(movie_details)
    movies_df <- rbind(movies_df, movie_details_df)
  }
}

print(movies_df)


```

## Trying for every URL

```{r}
movies_df_final <- data.frame(
  Title = character(),
  Year = character(),
  MPAA = character(),
  Duration = character(),
  IMDbscore = character(),
  Director = character(),
  FirstActor = character(),
  SecondActor = character(),
  FirstWriter = character(),
  SecondWriter = character(),
  ReleaseDate = character(),
  Genre = character(),
  Budget = character(),
  GrossWorldwide = character(),
  TitleReview = character(),
  FeatureReview = character(),
  AwardsAndNominations = character(),
  Oscar_Information = character(),
  stringsAsFactors = FALSE
)

for (url in full_movie_urls) {
  print(paste("Processing:", url))
  Sys.sleep(runif(1, 1, 3)) 
  movie_details <- tryCatch({
    scrape_movie_details(url)
  }, error = function(e) {
    print(paste("Error in processing:", url))
    print(e)
    return(NULL)
  })
  
  if (!is.null(movie_details)) {
    movie_details_df <- as.data.frame(matrix(unlist(movie_details), nrow = 1, byrow = TRUE), stringsAsFactors = FALSE)
    colnames(movie_details_df) <- names(movie_details)
    movies_df_final <- rbind(movies_df_final, movie_details_df)
  }
}

print(movies_df_final)

```

## Sensitive analysis of the Feature Reviews

```{r}
# the objective is to perform a sentiment analysis for each row of reviews we attain for each movie. Thus creating a variable that classify the sentiment of each review if it is positive or negative, and in some instances neutral.

Review_Sentiment <- function(review) {
  sentiment_score <- data_frame(text = review) %>%
    unnest_tokens(word, text) %>%
    inner_join(get_sentiments("bing"), by = "word") %>%
    summarise(net_sentiment = sum(case_when(
      sentiment == "positive" ~ 1,
      sentiment == "negative" ~ -1,
      TRUE ~ 0
    ))) %>%
    pull(net_sentiment)
  
  if (sentiment_score > 0) {
    return("positive")
  } else if (sentiment_score < 0) {
    return("negative")
  } else {
    return("neutral") 
  }
}

movies_df_final <- movies_df_final %>%
  mutate(ReviewClassification = map_chr(FeatureReview, Review_Sentiment))


```

## Descriptive analysis to understand the distribution of the data set.

```{r}
# Graph of the top genres of movies in my data set with their respective count of reviews sentiments

top_n_genres <- 6

top_genres <- movies_df_final %>%
  count(Genre, sort = TRUE) %>%
  top_n(top_n_genres, n)

filtered_movies <- movies_df_final %>%
  filter(Genre %in% top_genres$Genre)

Plot <- ggplot(filtered_movies, aes(x = ReviewClassification, fill = ReviewClassification)) +
  geom_bar(position = position_dodge(), color = "grey") +
  facet_wrap(~ Genre, scales = "free_x") +
  theme_light() +
  labs(title = "Top Genres by Review Classification",
       x = NULL, y = NULL) +
  scale_fill_manual(values = c("negative" = "#8dd3c7", "neutral" = "#ffffb3", "positive" = "#bebada")) +
theme(
    strip.text.x = element_text(size = 12, family = "sans"),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, family = "sans"),
    axis.text.y = element_text(family = "sans"),
    panel.spacing = unit(1, "lines"),
    plot.title = element_text(hjust = 0.5, face = "bold", family = "sans"),
    legend.position = "none"
  )
print(Plot)

```

```{r}
# distribution of the movies per decade
year <- as.numeric(movies_df_final$Year)
movies_df_final <- movies_df_final %>%
  mutate(Decade = floor(year / 10) * 10) 

movies_per_decade <- movies_df_final %>%
  group_by(Decade) %>%
  summarise(Count = n()) %>%
  mutate(Decade = factor(Decade, levels = unique(Decade)))

Plot2 <- ggplot(movies_per_decade, aes(x = Decade, y = Count)) +
  geom_bar(stat = "identity", fill = "#8856a7", width = 0.7) +
  theme_light() +
  labs(title = "Number of Movies from the Top250 per Decade",
       x = NULL,
       y = NULL) +
  theme(
    plot.title = element_text(face = "bold", family = "sans", size = 14),
    axis.title = element_text(family = "sans", size = 11),
    axis.text = element_text(family = "sans", size = 10),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    legend.position = "none"
  )

print(Plot2)



```

```{r}
movies_df_final$Budget <- as.numeric(gsub("[^0-9]", "", movies_df_final$Budget))
movies_df_final$IMDbscore <- as.numeric(movies_df_final$IMDbscore)
movies_df_final <- na.omit(movies_df_final)

Plot3 <- ggplot(movies_df_final, aes(x = Budget, y = IMDbscore, size = Budget, color = IMDbscore)) +
  geom_point(alpha = 1) +
  scale_size_continuous(range = c(1, 8)) + 
  scale_color_gradient(low = "blue", high = "red", limits = c(1, 10)) + 
  scale_x_continuous(labels = dollar_format(prefix = "$", suffix = "")) +
  scale_y_continuous(limits = c(1, 10), breaks = seq(1, 10, by = 1)) + 
  theme_light() +
  labs(title = "Bubble Chart of Movie Budgets vs. IMDB Score",
       x = NULL,
       y = NULL,
       size = "Budget",
       color = "IMDB Score") +
  theme(
    plot.title = element_text(face = "bold", family = "sans", size = 14),
    axis.title = element_text(family = "sans", size = 12),
    axis.text = element_text(family = "sans", size = 10),
    legend.position = "right"
  ) +
  guides(size = FALSE, color = guide_legend()) 


print(Plot3)


```
